name: tani_pintar_nusantara
description: Aplikasi Tani Pintar Nusantara
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.3.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+4
  camera: ^0.10.0+4
  shared_preferences: ^2.0.15
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/images/tim.jpg

# Konfigurasi localization
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  synthetic-package: false
